item_list = [
    ["Abyssal Scepter", 2],
    ["Aegis of the Legion", 2],
    ["Amplifying Tome", 1],
    ["Archangel's Staff", 3],
    ["Atma's Impaler", 2],
    ["Avarice Blade", 2],
    ["B. F. Sword", 1],
    ["Banshee's Veil", 3],
    ["Berserker's Greaves", 8],
    ["Bilgewater Cutlass", 2],
    ["Blasting Wand", 1],
    ["Boots of Mobility", 8],
    ["Boots of Speed", 1],
    ["Boots of Swiftness", 8],
    ["Brawler's Gloves", 1],
    ["Catalyst the Protector", 2],
    ["Chain Vest", 1],
    ["Chalice of Harmony", 2],
    ["Cloak and Dagger", 2],
    ["Cloak of Agility", 1],
    ["Cloth Armor", 1],
    ["Dagger", 1],
    ["Deathfire Grasp", 3],
    ["Doran's Blade", 1],
    ["Doran's Ring", 1],
    ["Doran's Shield", 1],
    ["Eleisa's Miracle", 2],
    ["Elixir of Agility", 0],
    ["Elixir of Brilliance", 0],
    ["Elixir of Fortitude", 0],
    ["Emblem of Valour", 2],
    ["Executioner's Calling", 2],
    ["Faerie Charm", 1],
    ["Fiendish Codex", 2],
    ["Force of Nature", 2],
    ["Frozen Heart", 3],
    ["Frozen Mallet", 3],
    ["Giant's Belt", 1],
    ["Glacial Shroud", 2],
    ["Guardian Angel", 2],
    ["Guinsoo's Rageblade", 2],
    ["Haunting Guise", 2],
    ["Health Potion", 0],
    ["Heart of Gold", 2],
    ["Hexdrinker", 2],
    ["Hextech Gunblade", 3],
    ["Hextech Revolver", 2],
    ["Infinity Edge", 2],
    ["Ionian Boots of Lucidity", 8],
    ["Kage's Lucky Pick", 2],
    ["Kindlegem", 2],
    ["Last Whisper", 2],
    ["Leviathan", 2],
    ["Lich Bane", 3],
    ["Long Sword", 1],
    ["Madred's Bloodrazor", 3],
    ["Madred's Razors", 2],
    ["Malady", 2],
    ["Mana Manipulator", 1],
    ["Mana Potion", 0],
    ["Manamune", 3],
    ["Mejai's Soulstealer", 2],
    ["Meki Pendant", 1],
    ["Mercury's Treads", 8],
    ["Moonflair Spellblade", 2],
    ["Morello's Evil Tome", 3],
    ["Nashor's Tooth", 3],
    ["Needlessly Large Rod", 1],
    ["Negatron Cloak", 1],
    ["Ninja Tabi", 8],
    ["Null-Magic Mantle", 1],
    ["Oracle's Elixir", 0],
    ["Phage", 2],
    ["Phantom Dancer", 3],
    ["Philosopher's Stone", 2],
    ["Pickaxe", 1],
    ["Quicksilver Sash", 2],
    ["Rabadon's Deathcap", 2],
    ["Randuin's Omen", 3],
    ["Recurve Bow", 1],
    ["Regrowth Pendant", 1],
    ["Rejuvenation Bead", 1],
    ["Rod of Ages", 3],
    ["Ruby Crystal", 1],
    ["Rylai's Crystal Scepter", 2],
    ["Sapphire Crystal", 1],
    ["Sheen", 2],
    ["Shurelya's Reverie", 3],
    ["Sight Ward", 0],
    ["Sorcerer's Shoes", 2],
    ["Soul Shroud", 2],
    ["Spirit Visage", 2],
    ["Stark's Fervor", 3],
    ["Stinger", 2],
    ["Sunfire Cape", 2],
    ["Sword of the Divine", 2],
    ["Sword of the Occult", 2],
    ["Tear of the Goddess", 2],
    ["The Black Cleaver", 2],
    ["The Bloodthirster", 2],
    ["The Brutalizer", 2],
    ["Thornmail", 2],
    ["Tiamat", 2],
    ["Trinity Force", 3],
    ["Vampiric Scepter", 1],
    ["Vision Ward", 0],
    ["Void Staff", 2],
    ["Warden's Mail", 2],
    ["Warmog's Armor", 2],
    ["Will of the Ancients", 3],
    ["Wit's End", 2],
    ["Wriggle's Lantern", 3],
    ["Youmuu's Ghostblade", 3],
    ["Zeal", 2],
    ["Zhonya's Hourglass", 2]
]

champ_list = [
    #Types: 0 - Hybrid, 1 - AD, 2 - AP, 3 - TankCaster, 4 - Support
    ["Akali", 0],
    ["Alistar", 3],
    ["Amumu", 3],
    ["Anivia", 2],
    ["Annie", 2],
    ["Ashe", 1],
    ["Blitzcrank", 0],
    ["Brand", 2],
    ["Caitlyn", 1],
    ["Cassiopeia", 2],
    ["Cho'Gath", 3],
    ["Corki", 1],
    ["Dr. Mundo", 1],
    ["Evelynn", 0],
    ["Ezreal", 0],
    ["Fiddlesticks", 2],
    ["Galio", 3],
    ["Gangplank", 1],
    ["Garen", 1],
    ["Gragas", 2],
    ["Heimerdinger", 2],
    ["Irelia", 1],
    ["Janna", 4],
    ["Jarvan IV", 1],
    ["Jax", 0],
    ["Karma", 4],
    ["Karthus", 2],
    ["Kassadin", 2],
    ["Katarina", 2],
    ["Kayle", 0],
    ["Kennen", 2],
    ["Kog'Maw", 0],
    ["LeBlanc", 2],
    ["Lee Sin", 1],
    ["Leona", 3],
    ["Lux", 2],
    ["Malphite", 3],
    ["Malzahar", 2],
    ["Maokai", 3],
    ["Master Yi", 1],
    ["Miss Fortune", 1],
    ["Mordekaiser", 3],
    ["Morgana", 2],
    ["Nasus", 1],
    ["Nidalee", 2],
    ["Nocturne", 1],
    ["Nunu", 3],
    ["Olaf", 1],
    ["Orianna", 2],
    ["Pantheon", 1],
    ["Poppy", 0],
    ["Rammus", 3],
    ["Renekton", 1],
    ["Rumble", 3],
    ["Ryze", 3],
    ["Shaco", 0],
    ["Shen", 3],
    ["Singed", 3],
    ["Sion", 0],
    ["Sivir", 1],
    ["Sona", 4],
    ["Soraka", 4],
    ["Swain", 2],
    ["Taric", 4],
    ["Teemo", 0],
    ["Tristana", 1],
    ["Trundle", 2],
    ["Tryndamere", 1],
    ["Twisted Fate", 0],
    ["Twitch", 1],
    ["Udyr", 1],
    ["Urgot", 1],
    ["Vayne", 1],
    ["Veigar", 2],
    ["Vladimir", 2],
    ["Warwick", 0],
    ["Wukong", 1],
    ["Xin Zhao", 1],
    ["Yorick", 1],
    ["Zilean", 4]

]

spell_list = [

    ["Exhaust"],
    ["Ghost"],
    ["Heal"],
    ["Revive"],
    ["Smite"],
    ["Teleport"],
    ["Cleanse"],
    ["Fortify"],
    ["Clarity"],
    ["Ignite"],
    ["Rally"],
    ["Clairvoyance"],
    ["Flash"]
]


item_list.each do |item|
  Item.create(:name => item[0], :tier => item[1])
end


champ_list.each do |champ|
  Champ.create(:name => champ[0], :ty => champ[1])
end


spell_list.each do |spell|
  Spell.create(:name => spell[0])
end

#rails generate model item name:string tier:integer
#rails generate model champ name:string ty:integer
#rails generate model spell name:string